import type { Lang } from './lang'

export function strings(lang: Lang) {
  const zh = lang === 'zh'
  return {
    langLabel: zh ? '中/EN' : 'EN/中',
    greeting: (name: string | null) => `你好呀～${name?.trim() || '朋友'}`,
    tapToSetName: zh ? '点击设置昵称' : 'Tap to set name',
    chooseTask: zh ? '选择一个任务开始计数。' : 'Choose a task to start counting.',
    noTasks: zh ? '还没有任务，先添加一个吧。' : 'No tasks yet. Add one to begin.',
    today: zh ? '今天' : 'Today',
    total: zh ? '总计' : 'Total',
    streakCn: zh ? '连续' : 'Streak',
    days: zh ? '天' : 'days',
    createTask: zh ? '+ 新建任务' : '+ New task',
    logout: zh ? '退出登录' : 'Log out',
    modalCreateTitle: zh ? '新建任务' : 'New task',
    modalName: zh ? '名称' : 'Name',
    modalNamePh: zh ? '例如：喝水' : 'e.g. Water',
    modalTotal: zh ? '总计（可为 0）' : 'Total (can be 0)',
    cancel: zh ? '取消' : 'Cancel',
    create: zh ? '创建' : 'Create',
    saving: zh ? '保存中…' : 'Saving…',
    save: zh ? '保存' : 'Save',
    deleting: zh ? '删除中…' : 'Deleting…',
    delete: zh ? '删除' : 'Delete',
    deleteConfirmTitle: zh ? '删除任务？' : 'Delete task?',
    deleteConfirmBody: (taskName: string) =>
      zh ? `将删除「${taskName}」以及它的所有记录。` : `This will delete “${taskName}” and all its history.`,
    renameTitle: zh ? '重命名任务' : 'Rename task',
    nicknameTitle: zh ? '昵称' : 'Display name',
    displayNameLabel: zh ? '显示名称' : 'Display name',
    taskNameLabel: zh ? '任务名称' : 'Task name',
    retry: zh ? '重试' : 'Retry',
    pleaseWait: zh ? '请稍候…' : 'Please wait…',
    signUp: zh ? '注册' : 'Sign up',
    logIn: zh ? '登录' : 'Log in',
    welcomeBack: zh ? '欢迎回来' : 'Welcome back',
    createAccount: zh ? '创建账号' : 'Create your account',
    alreadyHave: zh ? '已有账号？去登录' : 'Already have an account? Log in',
    needAccount: zh ? '没有账号？去注册' : 'Need an account? Sign up',
    email: zh ? '邮箱' : 'Email',
    password: zh ? '密码' : 'Password',
    checkEmail: zh ? '请查收邮箱确认后再登录。' : 'Check your email to confirm, then sign in.',
    somethingWrong: zh ? '出错了，请稍后再试。' : 'Something went wrong.',
    smallSteps: zh ? '慢慢来，都会变好。' : 'Small steps, lasting change.',
    smallSteps2: zh ? '今天做一点点就够了。' : 'Tiny steps add up.',
    smallSteps3: zh ? '坚持，比完美更重要。' : 'Consistency over perfection.',
    smallSteps4: zh ? '每次 +1，都算数。' : 'Every +1 counts.',
    calendarTitle: zh ? '日历' : 'Calendar',
    monthEmpty: zh ? '本月暂无记录' : 'No entries this month',
    prevMonth: zh ? '上个月' : 'Previous month',
    nextMonth: zh ? '下个月' : 'Next month',
    activityTitle: zh ? '最近记录' : 'Recent activity',
    activityToday: zh ? '今天' : 'Today',
    activityYesterday: zh ? '昨天' : 'Yesterday',
  }
}

